version: '3.8'

services:

  mcd-frontend-website-staging:

    image: 979699864122.dkr.ecr.ap-south-1.amazonaws.com/mcd-frontend-website-staging:latest

    container_name: mcd-frontend-website-staging

    working_dir: /app

    ports:
      - "3001:3001"

    restart: unless-stopped

    networks:
      - mcd_network

networks:
  mcd_network:
    driver: bridge