
export const PROJECT_VENUE_ROWS = [
  ['J.N. Sports Complex, Polo Ground Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Squash Court at Lower Lachumiere, Shillong', 'East Khasi Hills', 'Shillong'],
  ['Indoor Sports Hall (U Tirot Sing, Lower Lachumiere, Shillong)', 'East Khasi Hills', 'Shillong'],
  ['Crinoline Swimming Pool, Nongmalki Shillong', 'East Khasi Hills', 'Shillong'],
  ['Sitting Gallery cum VIP Rostrum Laban, Shillong', 'East Khasi Hills', 'Laban'],
  ['Basketball Court at Lummawbah, Shillong', 'East Khasi Hills', 'Shillong'],
  ['Sitting Gallery cum VIP Rostrum Nongumlong, Upper Shillong', 'East Khasi Hills', 'Upper Shillong'],
  ['Sitting Gallery at Nongkseh Upper Shillong', 'East Khasi Hills', 'Upper Shillong'],
  ['Playground at Umlympung', 'East Khasi Hills', 'Umlympung'],
  ['Gymnasium Hall at Nongthymmai, Shillong', 'East Khasi Hills', 'Shillong'],
  ['Basketball Court and Sitting Gallery at Seng Khasi Jaiaw, Shillong', 'East Khasi Hills', 'Jaiaw'],
  ['Basketball Court at Little Flower School Malki, Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Playfield at Madanrting, Shillong', 'East Khasi Hills', 'Shillong'],
  ['Playground at Balat', 'Ri Bhoi', 'Balat'],
  ['Playground at Lawsohtun, Shillong', 'East Khasi Hills', 'Shillong'],
  ['VIP Rostrum at Smit.', 'East Khasi Hills', 'Smit'],
  ['Indoor Sports Hall at Nongstoin, West Khasi Hills', 'West Khasi Hills', 'Nongstoin'],
  ['Indoor Sports Hall at Kynshi West Khasi Hills', 'West Khasi Hills', 'Kynshi'],
  ['Swimming Pool at Ranikor West Khasi Hills', 'West Khasi Hills', 'Ranikor'],
  ['Playground at Ummulong, Jaintia Hills', 'East Jaintia Hills', 'Ummulong'],
  ['Playground and Sitting Gallery at Bhoirymbong, Ri-Bhoi District', 'Ri Bhoi', 'Bhoirymbong'],
  ['Playground at Paham Syiem, Nongpoh, Ri-Bhoi District', 'Ri Bhoi', 'Nongpoh'],
  ['Basketball Court at Bhoirymbong, Ri-Bhoi District', 'Ri Bhoi', 'Bhoirymbong'],
  ['Indoor Sports Hall at Williamnagar East Garo Hills District', 'East Garo Hills', 'Williamnagar'],
  ['Playground and Sitting Gallery at Resubelpara, East Garo Hills District', 'East Garo Hills', 'Resubelpara'],
  ['Playground and sitting Gallery at Myndipathar, East Garo Hills District', 'East Garo Hills', 'Myndipathar'],
  ['Indoor Sports Hall at Tura, West Garo Hills District', 'West Garo Hills', 'Tura'],
  ['Playground at Tura, West Garo Hills District', 'West Garo Hills', 'Tura'],
  ['Playground at Gulpanibibra, South Garo Hills District.', 'South Garo Hills', 'Gulpanibibra'],
  ['Cricket Ground at J.N. Sports Complex, Polo Ground Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Indoor Sports Hall at Mawlai Datbaki Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Playground and Sitting Gallery at Pine Mount School Shillong', 'East Khasi Hills', 'Shillong'],
  ['Outdoor Stadium at Nongstoin West Khasi Hills District', 'West Khasi Hills', 'Nongstoin'],
  ['Indoor Sports Hall at Rangosora West Khasi Hills District', 'West Khasi Hills', 'Rangosora'],
  ['Playground at Laskein, Jaintia Hills District', 'Ext Jaintia Hills', 'Laskein'],
  ['Football Field at Saipung, Jaintia Hills District', 'East Jaintia Hills', 'Saipung'],
  ['Outdoor Stadium at Nongpoh, Ri-Bhoi District', 'Ri Bhoi', 'Nongpoh'],
  ['Playground at Nangalbibra, East Garo Hills District', 'East Garo Hills', 'Nangalbibra'],
  ['Playground including Sitting Gallery at Umthli Village', 'Ri Bhoi', 'Umthli'],
  ['Indoor Sports Hall at Jaiaw, Shillong', 'East Khasi Hills', 'Jaiaw'],
  ['Playground at Sohryngkham, East Khasi Hills District', 'East Khasi Hills', 'Sohryngkham'],
  ['Indoor Sports Hall at Mawsynram, East Khasi Hills District', 'East Khasi Hills', 'Mawsynram'],
  ['Playground at Mawten West Khasi Hills District', 'West Khasi Hills', 'Mawten'],
  ['Indoor Sports Hall at Saiden Ri-Bhoi District.', 'Ri Bhoi', 'Saiden'],
  ['Playfield at Kharpati, Garo Hills District', 'East Garo Hills', 'Kharpati'],
  ['Outdoor Playfield at Nongjri, Ri-Bhoi District', 'Ri Bhoi', 'Nongjri'],
  ['Playground at Kyrdem Ri-Bhoi District', 'Ri Bhoi', 'Kyrdem'],
  ['Indoor Sports Hall at Khimmusiang Jaintia Hills District', 'Ext Jaintia Hills', 'Khimmusiang'],
  ['Indoor Sports Hall at Sohra East Khasi Hills District.', 'East Khasi Hills', 'Sohra'],
  ['Indoor Sports Hall at Mawlong, Shella East Khasi Hills District', 'East Khasi Hills', 'Shella'],
  ['Indoor Sports Hall at Mawlai Umjapung Shillong', 'East Khasi Hills', 'Shillong'],
  ['Indoor Sports Hall at Mawkyrwat, West Khasi Hills District.', 'West Khasi Hills', 'Mawkyrwat'],
  ['Playground and sitting Gallery at Marngar, Ri-Bhoi District', 'Ri Bhoi', 'Marngar'],
  ['Indoor Sports Hall at Rajaballa, West Garo Hills District', 'West Garo Hills', 'Rajaballa'],
  ['Indoor Sports Hall at Mindhipathar, East Garo Hills District.', 'East Garo Hills', 'Mindhipathar'],
  ['Gymnasium cum Indoor Sports Hall at J.N.S. complex, Shillong', 'East Khasi Hills', 'Shillong'],
  ['Basketball Court and Sitting Gallery at JNS Complex, Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Basketball Court and Sitting Gallery at Synod Higher Secondary School, Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Playground including VIP Rostrum at Sohlab Shella East Khasi Hills District', 'East Khasi Hills', 'Shella'],
  ['Office Building and Quarter of DSO, Baghmara South Garo Hills District', 'South Garo Hills', 'Baghmara'],
  ['Office Building and Quarter of DSO, Nongstoin West Khasi Hills District', 'West Khasi Hills', 'Nongstoin'],
  ['Office Building and Quarter of DSO,Nongpoh, Ri-Bhoi District', 'Ri Bhoi', 'Nongpoh'],
  ['Office Building and Quarter of DSO,Tura West Garo Hills District', 'West Garo Hills', 'Tura'],
  ['Office Building and Quarter of DSO, Jowai, Jaintia Hills District', 'Ext Jaintia Hills', 'Jowai'],
  ['Football Ground including VIP Rostrum at Ri-Bhoi Presbyterian School Nongpoh.', 'Ri Bhoi', 'Nongpoh'],
  ['Playfield and VIP Rostrum at Sibari,', 'Ri Bhoi', 'Sibari'],
  ['Playfield at Pongtung East Khasi Hills District', 'East Khasi Hills', 'Pongtung'],
  ['Playground and Sitting Gallery at Damalgre, West Garo Hills District', 'West Garo Hills', 'Damalgre'],
  ['Playground at Mawdeja, Sohryngkham East Khasi Hills District', 'East Khasi Hills', 'Sohryngkham'],
  ['Indoor Sports Hall at Ranikor East Khasi Hills District', 'East Khasi Hills', 'Ranikor'],
  ['Playground including Sitting Gallery at Jungal, Baghmara South Garo Hills District', 'South Garo Hills', 'Baghmara'],
  ['Indoor Sports Hall at Salsela West Garo Hills District', 'West Garo Hills', 'Salsela'],
  ['Playground at Khliehdieng Mihmyntdu, Jaintia Hills District', 'East Jaintia Hills', 'Khliehdieng Mihmyntdu'],
  ['Playground including VIP Rostrum at Nongbah Jaintia Hills District', 'East Jaintia Hills', 'Nongbah'],
  ['Playground at Shangpung, Skut Jaintia Hills District', 'East Jaintia Hills', 'Shangpung'],
  ['Training Hall at JNS Complex, Shillong.', 'East Khasi Hills', 'Shillong'],
  ['Lawn Tennis Complex, at JNS Shillong', 'East Khasi Hills', 'Shillong'],
  ['Playground and Sitting Gallery at Mendipathar, North Garo Hills District', 'North Garo Hills', 'Mendipathar'],
  ['Outdoor Playfield at Ampati, South West Garo Hills District', 'South West Garo Hills', 'Ampati'],
  ['Indoor Sports Hall at Betasing, South West Khasi Hills District', 'South West Khasi Hills', 'Betasing'],
  ['Multipurpose Sports Ground at Mairang, Eastern West Khasi Hills District', 'Eastern West Khasi Hills', 'Mairang'],
] as const satisfies ReadonlyArray<readonly [string, string, string]>;
